set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR RISC-V)

set(RISCV_TOOLCHAIN_DIR "/home/batyrshin/secdisk2/work/ch32/ch32tools/xpack-riscv-none-elf-gcc-14.2.0-3/bin")

set(BINUTILS_PATH ${RISCV_TOOLCHAIN_DIR})

set(TOOLCHAIN_PREFIX ${RISCV_TOOLCHAIN_DIR}/riscv-none-elf-)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}gcc")
set(CMAKE_ASM_COMPILER  "${TOOLCHAIN_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX}g++")

set(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}objcopy CACHE INTERNAL "objcopy tool")
set(CMAKE_SIZE_UTIL ${TOOLCHAIN_PREFIX}size CACHE INTERNAL "size tool")

set(CMAKE_FIND_ROOT_PATH ${BINUTILS_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)



set(BASE_SOURCE_PREFIX ${CMAKE_SOURCE_DIR}/../ch32v3x)